version: '3.9'
services:
  nestjs:
    build: 
      context: ./brand-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./brand-api:/usr/src/app
      - '/usr/src/app/node_modules'
    environment:
      - DATABASE_PATH=/usr/src/app/database.sqlite
      - PYTHON_API_URL=http://python_app:5000
    depends_on:
      - python_app

  python_app:
    build: 
      context: ./ocr-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ocr-api:/usr/src/app